packages:
  - '.'

# Dependencias opcionales ignoradas en la construcción (optimiza instalaciones en Windows)
ignoredBuiltDependencies:
  - '@parcel/watcher'
  - esbuild
  - lmdb
  - msgpackr-extract
